name: Update Lessentabellen Files

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Bestand om aan te passen'
        required: true
      changes:
        description: 'Wijzigingen'
        required: true

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Update file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ github.event.inputs.changes }}" > "${{ github.event.inputs.file }}"
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update ${{ github.event.inputs.file }}
        title: Update ${{ github.event.inputs.file }}
        body: Wijziging aangebracht via geautomatiseerde workflow
        branch: update-${{ github.event.inputs.file }}
